version: "3.8"
services:
  webapp:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/demo
    container_name: django-demo
    hostname: django-dev-demo
    volumes:
       - ./app:/app
    # command: sleep 3600