version: "3.8"
services:
  webapp:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/pro
    container_name: django-pro
    hostname: django-dev-pro
    ports:
      - 8080:8080
    volumes:
       - ./app:/app
    # command: sleep 3600